apiVersion: arks.ai/v1
kind: ArksToken
metadata:
  name: example-token
  namespace: default
spec:
  token: "sk-test123456"
  qos:
    - arksEndpoint:
        name: qwen-7b
      rateLimits:
        - type: rpm     
          value: 60
        - type: tpm      
          value: 40000
        - type: rpd    
          value: 1000
        - type: tpd   
          value: 1000000
      quota:
        name: basic-quota   
    