apiVersion: arks.ai/v1
kind: ArksApplication
metadata:
  labels:
    app.kubernetes.io/name: arks-operator
    app.kubernetes.io/managed-by: kustomize
  name: app-qwen
spec:
  replicas: 1
  size: 1
  tensorParallelSize: 2
  extraOptions:
    - --mem-fraction-static
    - "0.7"
  runtime: sglang
  # Optional, default to spec.model.name
  # servedModelName: qwen-7b
  model:
    name: qwen-7b
  instanceSpec:
    resources:
      limits:
        nvidia.com/gpu: "1"
      requests:
        nvidia.com/gpu: "1"
