apiVersion: arks.scitix.ai/v1
kind: ArksQuota
metadata:
  name: basic-quota
  namespace: default
spec:
  quotas:
    - type: prompt   
      value: 100000
    - type: response
      value: 500000
    - type: total   
      value: 600000