apiVersion: arks.scitix.ai/v1
kind: ArksApplication
metadata:
  labels:
    app.kubernetes.io/name: arks-operator
    app.kubernetes.io/managed-by: kustomize
  name: app-qwen
spec:
  replicas: 1
  tensorParallelSize: 2
  runtime: dynamo
  servedModelName: myqwen-7b
  model:
    name: qwen-7b
  instanceSpec:
    replicas: 2
    env:
    - name: ETCD_ENDPOINTS
      value: http://dynamo-platform-etcd.dynamo-playground:2379
    - name: NATS_SERVER
      value: nats://dynamo-platform-nats.dynamo-playground:4222
    resources:
      limits:
        nvidia.com/gpu: "1"
      requests:
        nvidia.com/gpu: "1"