apiVersion: arks.scitix.ai/v1
kind: ArksApplication
metadata:
  labels:
    app.kubernetes.io/name: arks-operator
    app.kubernetes.io/managed-by: kustomize
  name: app-qwen-vllm
spec:
  replicas: 1
  tensorParallelSize: 2
  runtime: vllm
  # Optional, default to spec.model.name
  # servedModelName: qwen-7b
  model:
    name: qwen-7b
  instanceSpec:
    replicas: 2
    resources:
      limits:
        nvidia.com/gpu: "1"
      requests:
        nvidia.com/gpu: "1"
