## Append samples of your project ##
resources:
- arks_v1_arksapplication.yaml
- arks_v1_arkstoken.yaml
- arks_v1_arksquota.yaml
- arks_v1_arksmodel.yaml
- arks_v1_arksendpoint.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
